package provaRecuperacao;

public interface Funcionario {
	String obterInformacoesFuncionario();
	boolean temInsalubridade();
}
public  void Gerente(){
	String nome;
	int hoharioDeTrabalho;
	int CPF;
	int InicioNaEmpresa;

}	
public void OperadorMaquina(){
	String nome;
	int hoharioDeTrabalho;
	int CPF;
	int anoDeInicioNaEmpresa;
}
public void Engenheiro(){
	String nome;
	int hoharioDeTrabalho;
	int CPF;
	int anoDeInicioNaEmpresa;

}